"""
Django settings for analytics_engine project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y*q$^h#)!ty@g)yxny(j-!pq7_)z&5!phu($1j264s)@3m=t-x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'analytics_engine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'analytics_engine.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

VENTURA_FIREBASE_PRIVATE_KEY = {
  "type": "service_account",
  "project_id": "ventura-bfe66",
  "private_key_id": "39983ffe5cd1631b5491c2023d2f9a4b2938a6c4",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDLfihlTQVmyXmc\n2ZrDSYzWKTdMOuC/8g7e73ecmZy4+DeW5XezVgO77jNS2Ax4VaxsiaEe6LPvdxaj\ndcOhyFQY1AAy5LkhZyVzE/60eChW7Enh5nTn/gPcgdJSCt0vtKcgHbXq7J/aDFgn\nIzA90XhSBLcYw5BnuquS2w+26ZVteMmfV3c8KcuH2vOmrDsLqpFi6ubW86XiNP+q\nQ7W5Se+czXHkqnlsB3PwiQB5+0uHm1EuYQa/E18cuiVfRl2xhA4alvczGUTHeqG0\n17gLTJSV8olxUCSEHOLVEks+o2ILovKYNdT6srCFZ0IkL6rEQfkbXYkwexz1yMmJ\nnhZ1ayKpAgMBAAECggEAA4TmIzFYrHFDyYUAXov3M+1wy8BRanRf0jZrN8G20oKV\naIZFoov0YtPA3rgGiC64HYToTMnqsbOaKD/FPzchEDBbZAXtVzDq1oGEJEAXN4Cc\n2vuiri/oBnBW0C0oq9ZolP86igpnTcysmhmrUAhfN7Dl7zdTmB2j8bVY4VmLCGJ4\nVt11o2QLJBR7R+ur4vTORuYutPWDJBj4550LdRNz0UR35wsiNGWjzi5pOJjWjKMT\nS8t5VZWJ5Myu9JstTZVLxA4om+ZdILOYerRCgyUarCZUtsNlak0AJyKnBFRiCJdG\n6Mp7nR0tvAmu6iXZJpBqS+OfbPQebOG884ybIE3bMQKBgQDxvEhekv6rswIDZ+zE\n3IdwNpTso84RBuQmRW2OOHWvZxuuoQoJH86eyPUjqN46KR8vl5Fy6jiIQpPi4gFL\npxXnKiVCMAUCOfo13alub85EJ8Mc5/hlkb8I//wJ2WbP0/7FS93T+xVPrMfUc540\njzs4Ta7snG3sOseY0KckRpoMOQKBgQDXgCvsOcWAiLp6FB/7Ttt5jny/TKY47ezC\nHAgkJPJt19XrsWSyBSnLZdA/3F2bRVQGg3dCgPFugbPMAmu+YV6SmhB810QGrm3G\nJpP3d5wO0ChIhDxYuPUHD6kYfPKg2T2S12v8r10J1fWGhH3bMVAUrNXtZVBUnbeQ\nmP2R1vSp8QKBgQCr468uGKYgXyxaUaapoQppf1ZMInof31+R2yJ406rTK6Uien5R\nWJ2qiMjPL3+9qYn0ZHlXVjcWpQjVdtFnAwtvEafmtZCKMcG6VcDpt3TbP87cmhIl\n3woREz0bn8wckekCT90Po+VWf0ykxAXF5+c7NPniY6VCKdXN0uhWwiE9+QKBgDSP\n9aajnLGyJ9G48OgKHuwyPeknF/AQ0Eu0LKQsQtlZ6LqZRRdKvRv4VGgPJuHFci44\niLE25CxxBFrBSGhiNYAKhfT9SIFcsDfBlxuoF+9hBEJTxqhZTKKRRkxLxZ5H/oW/\nd35lg4rvnfhWfqAlEgRI99D0gjhxU6G4PzkANiLxAoGANeIZv/SNbNUEsrfYFQtT\n1lLN1tYVor2FrqyBrjs6Hl/KX0VRah/2jf8Ist3SH2IScEOisMhYSCB1casEQJ+/\nRF9p5aiRnWu4bSUGPBn5WYdNnFkdnKxnhNoyYdtvUTqLmcsBtIUJbU3MxUVFqX0l\nMWTM5n1dyqg3+zqr+fW+Y/U=\n-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-54br6@ventura-bfe66.iam.gserviceaccount.com",
  "client_id": "107896651163926644005",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-54br6%40ventura-bfe66.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}

# Firebase storage stored globally
FIREBASE_BUCKET = None
